### ISSUE TITLE
Need to update to CRI runtime API v1alpha2

### ISSUE THREAD

**Issue by mestery** [contiv/vpp#1043]
As part of trying to get ligato/cn-infra, ligato/vpp-agent and contiv/vpp up the kubernetes-1.11, a breaking API change for CRI was introduced. The previous API was v1alpha1, and it has been upgraded to v1alpha2.

I tried to make an attempt at this change earlier this week, but I was unable to complete it. Someone with more knowledge of the CRI stuff inside of contiv/vpp can likely make this change much faster.

This will be required to upgrade the kubernetes dependency to at least 1.10 (and ideally 1.11) where we can make use of CRDs.

/cc @jhnbrns @jmedved @ondrej-fabry

**Comment by jmedved** [comment]
We can deprecate CRI for now and take it out of the build. It’s not used. IF& when we use it in the future, we will re-introduce the latest version at that time.

/Jan

**Comment by brecode** [comment]
Closing this since Contiv-CRI is now deprecate #1047 
@mestery @jmedved
