### ISSUE TITLE
The contiv-vswitch daemonset is not working on kubernets 1.12.1

### ISSUE THREAD

**Issue by diuming** [contiv/vpp#1157]
Issue
---
I follow the (https://github.com/contiv/vpp/blob/master/docs/MANUAL_INSTALL.md) to install k8s and contiv-vpp.
Two docker images `contiv-vswitch` and `contiv-cni` are not downloaded and daemonset `contiv-vswitch` is not working.

My `contiv-vpp.yaml`(https://raw.githubusercontent.com/contiv/vpp/master/k8s/contiv-vpp.yaml)
...
    CRDNodeConfigurationDisabled: true
    IPAMConfig:
    &nbsp;&nbsp;&nbsp;NodeInterconnectDHCP: false
    &nbsp;&nbsp;&nbsp;NodeInterconnectCIDR: 192.168.16.0/24
    &nbsp;&nbsp;&nbsp;PodSubnetCIDR: 10.1.0.0/16
    &nbsp;&nbsp;&nbsp;PodNetworkPrefixLen: 24
    &nbsp;&nbsp;&nbsp;PodIfIPCIDR: 10.2.1.0/24
    &nbsp;&nbsp;&nbsp;VPPHostSubnetCIDR: 172.30.0.0/16
    &nbsp;&nbsp;&nbsp;VPPHostNetworkPrefixLen: 24
    &nbsp;&nbsp;&nbsp;VxlanCIDR: 192.168.30.0/24
    NodeConfig:
    - NodeName: "k8s-master"
    &nbsp;&nbsp;&nbsp;StealInterface: "enp0s8"
    - NodeName: "k8s-worker1"
    &nbsp;&nbsp;&nbsp;StealInterface: "enp0s8"
...

Versions
---
operation system version: ubuntu 16.04
docker version: 18.06.1-ce
kubernetes version: 1.12.1
> cri-tools/kubernetes-xenial,now 1.12.0-00
kubeadm/kubernetes-xenial,now 1.12.1-00
kubectl/kubernetes-xenial,now 1.12.1-00
kubelet/kubernetes-xenial,now 1.12.1-00
kubernetes-cni/kubernetes-xenial,now 0.6.0-00

Current daemonset information
---
NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR
contiv-crd       1         1         0       1            0           node-role.kubernetes.io/master=   75m
contiv-ksr       1         1         0       1            0           node-role.kubernetes.io/master=   75m
contiv-vswitch   0         0         0       0            0           <none>                            75m
kube-proxy       1         1         1       1            1           <none>                            81m

**Comment by rastislavszabo** [comment]
Could you provide some more info? E.g.
- kubectl describe pod of the vswitch pods
- logs of the vswitch pod
- previous logs of the vswtich pod

You can obtain it all using the `scripts/contiv-vpp-bug-report.sh` script.

**Comment by diuming** [comment]
@rastislavszabo
I can't find any contiv-vswitch pods.

kubectl get pods --all-namespaces
---
NAMESPACE     NAME                                 READY   STATUS             RESTARTS   AGE
kube-system   contiv-crd-qnkh4                     0/1     CrashLoopBackOff   7          16m
kube-system   contiv-etcd-0                        1/1     Unknown            0          15s
kube-system   contiv-ksr-fhhfg                     0/1     CrashLoopBackOff   7          16m
kube-system   coredns-576cbf47c7-ltf6g             0/1     Pending            0          98m
kube-system   coredns-576cbf47c7-rdxjt             0/1     Pending            0          98m
kube-system   etcd-k8s-master                      0/1     Pending            0          4s
kube-system   kube-apiserver-k8s-master            0/1     Pending            0          4s
kube-system   kube-controller-manager-k8s-master   0/1     Pending            0          4s
kube-system   kube-proxy-jl9q7                     1/1     NodeLost           1          98m
kube-system   kube-scheduler-k8s-master            0/1     Pending            0          4s

kubectl get daemonset --all-namespaces
---
NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                    
contiv-crd       1         1         0       1            0           node-role.kubernetes.io/master=
contiv-ksr       1         1         0       1            0           node-role.kubernetes.io/master=
contiv-vswitch   0         0         0       0            0           <none>                       
kube-proxy       1         1         1       1            1           <none>

**Comment by rastislavszabo** [comment]
I can confirm that there are some issues with Contiv-VPP on k8s 1.12. Looking into it.
In the meantime, 1.11.x versions are well tested and supported.

**Comment by diuming** [comment]
@rastislavszabo thank you for helping.
it works fine so far.
