### ISSUE TITLE
Why the contiv-vpp running so many times?

### ISSUE THREAD

**Issue by diuming** [contiv/vpp#1176]
## Issue
...
/usr/bin/vpp[2281] DPDK: EAL init args: -c -n 4 --huge-dir /run/vpp/hugepages --file-prefix vpp -w 0000:00:08.0 --master-1core0 --docket-mem 64
/usr/bin/vpp[17820] DPDK: EAL init args: -c -n 4 --huge-dir /run/vpp/hugepages --file-prefix vpp -w 0000:00:08.0 --master-1core0 --docket-mem 64
/usr/bin/vpp[26426] DPDK: EAL init args: -c -n 4 --huge-dir /run/vpp/hugepages --file-prefix vpp -w 0000:00:08.0 --master-1core0 --docket-mem 64
...

## Versions
OS: Ubuntu 18.04(VM)
K8s: 1.12.1
Docker: 18.06.1-ce

## kubectl get pods -n kube-system
NAME                                  READY   STATUS              RESTARTS   AGE
contiv-crd-2hw5t                      1/1     `Running`             0          16m
contiv-etcd-0                         1/1     `Running`             0          16m
contiv-ksr-82pjq                      1/1     `Running`             0          16m
contiv-vswitch-k2f2h                  0/1     `Running`             16         3h6m
coredns-576cbf47c7-ktbrw              0/1     `ContainerCreating (always)`   0          26h 
coredns-576cbf47c7-vcwcz              0/1     `ContainerCreating (always)`   0          26h 
etcd-k8s-master1                      1/1    ` Running`             7          26h
kube-apiserver-k8s-master1            1/1     `Running`             7          26h
kube-controller-manager-k8s-master1   1/1     `Running`             7          26h
kube-proxy-b8v2n                      1/1     `Running`             7          26h
kube-scheduler-k8s-master1            1/1     `Running`             7          26h

## kubectl describe pods coredns-576cbf47c7-ktbrw -n kube-system
  Warning  FailedCreatePodSandBox  30m                      kubelet, k8s-master1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c18f140f30783f1458e920e464b978827a542b38d15a9581830c2f05d885b13f" network for pod "coredns-576cbf47c7-ktbrw": NetworkPlugin cni failed to set up pod "coredns-576cbf47c7-ktbrw_kube-system" network: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /var/run/contiv/cni.sock: connect: no such file or directory"

**Comment by rastislavszabo** [comment]
Sorry, I don't understand your question. But from the logs I guess you were facing an issue with coredns PODs not being able to start? That was an issue with the latest contiv over the weekend, It is now fixed.

**Comment by diuming** [comment]
@rastislavszabo take a look, please
OS: ubuntu 18.04 ram: 2G(on virtualBox)
Is it a hugepage issue?

![contiv-vpp1](https://user-images.githubusercontent.com/39903550/47054668-c190ac00-d1e5-11e8-8dba-548ee83a4d3f.png)

![contiv-vpp2](https://user-images.githubusercontent.com/39903550/47054643-96a65800-d1e5-11e8-9a3d-cf0651b37470.png)

## /var/run/contiv/cni.log
...
D_NAME=coredns-576cbf47c7-szphd;K8S_POD_INFRA_CONTAINER_ID=46dfd46db43744338cc746f737db8dffb414912d6c897a565b035bf11dd3aa5e" ContainerID=46dfd46db43744338cc746f737db8dffb414912d6c897a565b035bf11dd3aa5e IfName=eth0 Netns=/proc/4825/ns/net
time="2018-10-17T00:23:19Z" level=error msg="Error by executing remote CNI Delete request: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /var/run/contiv/cni.sock: connect: no such file or directory\""
time="2018-10-17T00:23:20Z" level=debug msg="CNI DEL request" Args="IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=coredns-576cbf47c7-9p52t;K8S_POD_INFRA_CONTAINER_ID=a3b7c786bed9e0cd4dd8d6c397a8055d9a186ab915affff66027125dc7c2ccd8" ContainerID=a3b7c786bed9e0cd4dd8d6c397a8055d9a186ab915affff66027125dc7c2ccd8 IfName=eth0 Netns=
time="2018-10-17T00:23:20Z" level=error msg="Error by executing remote CNI Delete request: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /var/run/contiv/cni.sock: connect: no such file or directory\""
time="2018-10-17T00:23:20Z" level=debug msg="CNI DEL request" Args="IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=coredns-576cbf47c7-szphd;K8S_POD_INFRA_CONTAINER_ID=46dfd46db43744338cc746f737db8dffb414912d6c897a565b035bf11dd3aa5e" ContainerID=46dfd46db43744338cc746f737db8dffb414912d6c897a565b035bf11dd3aa5e IfName=eth0 Netns=
time="2018-10-17T00:23:20Z" level=error msg="Error by executing remote CNI Delete request: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /var/run/contiv/cni.sock: connect: no such file or directory\""
...

## kubectl describe pods contiv-vswitch-wgxkd -n kube-system
Name:               contiv-vswitch-wgxkd
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               k8s-master1/192.168.1.11
Start Time:         Tue, 16 Oct 2018 23:52:04 +0000
Labels:             controller-revision-hash=848d779d64
                    k8s-app=contiv-vswitch
                    pod-template-generation=1
Annotations:        scheduler.alpha.kubernetes.io/critical-pod: 
Status:             Running
IP:                 192.168.1.11
Controlled By:      DaemonSet/contiv-vswitch
Init Containers:
  contiv-cni:
    Container ID:   docker://479f4e0ace2a77750a50f0f87229406b0aa389bb6654f04f531bf988da796557
    Image:          contivvpp/cni:latest
    Image ID:       docker-pullable://contivvpp/cni@sha256:86b7fdd290b7960b9de114c06f38ca40c41c5380f22c950438015887ac2b2b33
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 16 Oct 2018 23:52:42 +0000
      Finished:     Tue, 16 Oct 2018 23:52:42 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      SLEEP:  false
    Mounts:
      /etc/cni/net.d from cni-net-dir (rw)
      /opt/cni/bin from cni-bin-dir (rw)
      /var/run/contiv from contiv-run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zw878 (ro)
  wait-foretcd:
    Container ID:  docker://3699719de8231702a1c7c99132608b4eb31454594fc0c463c44845067cd9314e
    Image:         busybox:latest
    Image ID:      docker-pullable://busybox@sha256:2a03a6059f21e150ae84b0973863609494aad70f0a80eaeb64bddd8d92465812
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      until nc -w 2 127.0.0.1:$ETCDPORT; do echo waiting for etcd; sleep 2; done;
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 16 Oct 2018 23:52:59 +0000
      Finished:     Tue, 16 Oct 2018 23:52:59 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      ETCDPORT:  32379
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zw878 (ro)
  vpp-init:
    Container ID:  docker://af404451bfb7d1a8ebf0543375ff496a7fcece975292e662caf4be27835cb54a
    Image:         contivvpp/vswitch:latest
    Image ID:      docker-pullable://contivvpp/vswitch@sha256:207b1b93923110975dd5f464d97b8baed389505673bd251e02cff51283fe9ff2
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      set -eu
      chmod 700 /run/vpp
      rm -rf /dev/shm/db /dev/shm/global_vm /dev/shm/vpe-api
      if [ ! -e /host/etc/vpp/contiv-vswitch.conf ]; then
          cp /etc/vpp/contiv-vswitch.conf /host/etc/vpp/
      fi
      if [ ! -d /var/run/contiv ]; then
          mkdir /var/run/contiv
      fi
      chmod 700 /var/run/contiv
      rm -f /var/run/contiv/cni.sock
      if ip link show vpp1 >/dev/null 2>&1; then
           ip link del vpp1
      fi
      cp -f /usr/local/bin/vppctl /host/usr/local/bin/vppctl
      sysctl -w debug.exception-trace=1
      sysctl -w kernel.core_pattern="/var/contiv/dumps/%e-%t"
      ulimit -c unlimited
      echo 2 > /proc/sys/fs/suid_dumpable
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 16 Oct 2018 23:56:53 +0000
      Finished:     Tue, 16 Oct 2018 23:56:53 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /dev/shm from shm (rw)
      /host/etc/vpp from vpp-cfg (rw)
      /host/usr/local/bin from usr-local-bin (rw)
      /run/vpp from vpp-run (rw)
      /var/contiv/dumps from core-dumps (rw)
      /var/run/contiv from contiv-run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zw878 (ro)
      /vpp-lib64/ from vpp-lib64 (rw)
Containers:
  contiv-vswitch:
    Container ID:   docker://7c94a5616ccd9bb0ef0cb32f07f943ad3002ead220cef0fbab3502ceab7fbd5b
    Image:          contivvpp/vswitch:latest
    Image ID:       docker-pullable://contivvpp/vswitch@sha256:207b1b93923110975dd5f464d97b8baed389505673bd251e02cff51283fe9ff2
    Port:           9999/TCP
    Host Port:      9999/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 17 Oct 2018 00:13:44 +0000
      Finished:     Wed, 17 Oct 2018 00:14:50 +0000
    Ready:          False
    Restart Count:  9
    Liveness:       http-get http://:9999/liveness delay=60s timeout=2s period=3s #success=1 #failure=3
    Readiness:      http-get http://:9999/readiness delay=15s timeout=2s period=3s #success=1 #failure=3
    Environment:
      MICROSERVICE_LABEL:   (v1:spec.nodeName)
      ETCD_CONFIG:         /etc/etcd/etcd.conf
      BOLT_CONFIG:         /etc/agent/bolt.conf
      TELEMETRY_CONFIG:    /etc/agent/telemetry.conf
    Mounts:
      /dev from dev (rw)
      /dev/shm from shm (rw)
      /etc/agent from contiv-plugin-cfg (rw)
      /etc/etcd from etcd-cfg (rw)
      /etc/govpp from govpp-plugin-cfg (rw)
      /etc/vpp from vpp-cfg (rw)
      /run/vpp from vpp-run (rw)
      /var/bolt from var-bolt (rw)
      /var/contiv/dumps from core-dumps (rw)
      /var/run/contiv from contiv-run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zw878 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  etcd-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      contiv-etcd-cfg
    Optional:  false
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  vpp-cfg:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/vpp
    HostPathType:  
  usr-local-bin:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/local/bin
    HostPathType:  
  vpp-lib64:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/ldpreload/vpp-lib64
    HostPathType:  
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
  shm:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/shm
    HostPathType:  
  vpp-run:
    Type:          HostPath (bare host directory volume)
    Path:          /run/vpp
    HostPathType:  
  contiv-run:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/contiv
    HostPathType:  
  contiv-plugin-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      contiv-agent-cfg
    Optional:  false
  govpp-plugin-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      govpp-cfg
    Optional:  false
  core-dumps:
    Type:          HostPath (bare host directory volume)
    Path:          /var/contiv/dumps
    HostPathType:  
  var-bolt:
    Type:          HostPath (bare host directory volume)
    Path:          /var/bolt
    HostPathType:  
  default-token-zw878:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zw878
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                    From                  Message
  Normal   Scheduled  23m                    default-scheduler     Successfully assigned kube-system/contiv-vswitch-wgxkd to k8s-master1
  Normal   Pulling    23m                    kubelet, k8s-master1  pulling image "contivvpp/cni:latest"
  Normal   Pulled     22m                    kubelet, k8s-master1  Successfully pulled image "contivvpp/cni:latest"
  Normal   Created    22m                    kubelet, k8s-master1  Created container
  Normal   Started    22m                    kubelet, k8s-master1  Started container
  Normal   Pulling    22m                    kubelet, k8s-master1  pulling image "busybox:latest"
  Normal   Pulled     22m                    kubelet, k8s-master1  Successfully pulled image "busybox:latest"
  Normal   Created    22m                    kubelet, k8s-master1  Created container
  Normal   Started    22m                    kubelet, k8s-master1  Started container
  Normal   Pulling    22m                    kubelet, k8s-master1  pulling image "contivvpp/vswitch:latest"
  Normal   Pulled     18m                    kubelet, k8s-master1  Successfully pulled image "contivvpp/vswitch:latest"
  Normal   Created    18m                    kubelet, k8s-master1  Created container
  Normal   Started    18m                    kubelet, k8s-master1  Started container
  Normal   Pulled     18m                    kubelet, k8s-master1  Container image "contivvpp/vswitch:latest" already present on machine
  Normal   Created    18m                    kubelet, k8s-master1  Created container
  Normal   Started    18m                    kubelet, k8s-master1  Started container
  Warning  Unhealthy  8m32s (x134 over 18m)  kubelet, k8s-master1  Readiness probe failed: Get http://192.168.1.11:9999/readiness: dial tcp 192.168.1.11:9999: connect: connection refused
  Warning  BackOff    3m28s (x32 over 11m)   kubelet, k8s-master1  Back-off restarting failed container

**Comment by rastislavszabo** [comment]
yes, it seems like a hugepages / memory issue. 2 GB RAM is very low, I'm not sure if it is able to come up with that amount of memory (we test with 4GB). Also, please make sure you read this section of the documentation: 
https://github.com/contiv/vpp/blob/master/docs/MANUAL_INSTALL.md#using-kubernetes-110-and-above

**Comment by diuming** [comment]
@rastislavszabo 

I had already edited the /etc/default/kubelet file before with following.
```
Environment="KUBELET_EXTRA_ARGS=--feature-gates HugePages=false"
```
and now I increase memory up to 4G, but I get the same issue.
