### ISSUE TITLE
vswitch crash with NodeInterconnectDHCP: true ===> failed to config interface

### ISSUE THREAD

**Issue by qingzhhu** [contiv/vpp#1322]
**LOG**:

{"log":"2018-12-22 05:32:26,671 DEBG 'contiv-agent' stdout output:\n","stream":"stdout","time":"2018-12-22T05:32:26.671770816Z"}
{"log":"time=\"2018-12-22 05:32:26.67122\" level=debug msg=\"DHCP assigned 192.168.0.9 to interface \\\"host-192-168-0-9\\\" (router address 192.168.0.200)\" loc=\"ifplugin/interface_config.go(967)\" logger=vpp.if-conf\n","stream":"stdout","time":"2018-12-22T05:32:26.671805207Z"}
{"log":"time=\"2018-12-22 05:32:26.67129\" level=warning msg=\"Expected interface host-192-168-0-9 not found in the mapping\" loc=\"ifplugin/interface_config.go(971)\" logger=vpp.if-conf\n","stream":"stdout","time":"2018-12-22T05:32:26.671809504Z"}

**code** in vendor/github.com/ligato/vpp-agent/plugins/vpp/ifplugin/interface_config.go:
`                              
                               c.log.Debugf("DHCP assigned %v to interface %q (router address %v)", ipStr, name, rIPStr)

                                ifIdx, _, found := c.swIfIndexes.LookupIdx(name)
                                if !found {
                                        c.log.Warnf("Expected interface %v not found in the mapping", name)
                                        continue
                                }

                                // Register DHCP config
                                c.dhcpIndexes.RegisterName(name, ifIdx, &ifaceidx.DHCPSettings{
                                        IfName: name,
                                        IsIPv6: func(isIPv6 uint8) bool {
                                                if isIPv6 == 1 {
                                                        return true
                                                }
                                                return false
                                        }(dhcpNotif.Lease.IsIPv6),
                                        IPAddress:     ipStr,
                                        Mask:          uint32(dhcpNotif.Lease.MaskWidth),
                                        PhysAddress:   hwAddr.String(),
                                        RouterAddress: rIPStr,
                                })
                                c.log.Debugf("Interface %s registered as DHCP client", name)
`

**contiv-vpp.yaml**
`apiVersion: v1
kind: ConfigMap

metadata:
  name: contiv-agent-cfg
  namespace: kube-system
data:
  contiv.yaml: |-
    ...
    IPAMConfig:
      ...
      NodeInterconnectDHCP: true`

**Comment by qingzhhu** [comment]
any configuration for this ?

can not find interface 'host-192-168-0-9' ????

**Comment by rastislavszabo** [comment]
Hi,
please include full bug report information, as described here: https://github.com/contiv/vpp/blob/master/docs/BUG_REPORTS.md

You can collect all logs using the bug report script:
https://github.com/contiv/vpp/blob/master/scripts/contiv-vpp-bug-report.sh

**Comment by qingzhhu** [comment]
Fixed in lastest vpp2 code, so i will close this issue
