### ISSUE TITLE
No Nat in pod to internet

### ISSUE THREAD

**Issue by qingzhhu** [contiv/vpp#1323]
06:46:56.882763 fa:16:3e:df:e2:19 > fa:16:3e:42:1f:2b, ethertype IPv4 (0x0800), length 98: 10.1.1.2 > 31.134.97.51: ICMP echo request, id 3279, seq 203, length 64
06:46:57.882872 fa:16:3e:df:e2:19 > fa:16:3e:42:1f:2b, ethertype IPv4 (0x0800), length 98: 10.1.1.2 > 31.134.97.51: ICMP echo request, id 3279, seq 204, length 64
06:46:58.883082 fa:16:3e:df:e2:19 > fa:16:3e:42:1f:2b, ethertype IPv4 (0x0800), length 98: 10.1.1.2 > 31.134.97.51: ICMP echo request, id 3279, seq 205, length 64
06:46:59.882823 fa:16:3e:df:e2:19 > fa:16:3e:42:1f:2b, ethertype IPv4 (0x0800), length 98: 10.1.1.2 > 31.134.97.51: ICMP echo request, id 3279, seq 206, length 64
06:4

    _______    _        _   _____  ___
 __/ __/ _ \  (_)__    | | / / _ \/ _ \
 _/ _// // / / / _ \   | |/ / ___/ ___/
 /_/ /____(_)_/\___/   |___/_/  /_/

vpp# show interface addr
GigabitEthernet0/4/0 (up):
  L3 192.168.0.9/24
local0 (dn):
loop0 (up):
  L3 192.168.30.1/24 ip4 table-id 1 fib-idx 1
tap0 (up):
  L3 172.30.1.1/24
tap1 (up):
  L3 10.2.1.2/32 ip4 table-id 1 fib-idx 1
tap2 (up):
  L3 10.2.1.3/32 ip4 table-id 1 fib-idx 1
vpp# ping 31.134.97.51
64 bytes from 31.134.97.51: icmp_seq=1 ttl=52 time=42.0749 ms
64 bytes from 31.134.97.51: icmp_seq=2 ttl=52 time=29.9239 ms

**Comment by rastislavszabo** [comment]
Hi,
please include full bug report information, as described here: https://github.com/contiv/vpp/blob/master/docs/BUG_REPORTS.md

You can collect all logs using the bug report script:
https://github.com/contiv/vpp/blob/master/scripts/contiv-vpp-bug-report.sh
