### ISSUE TITLE
NodePort in Kubernetes 1.13.1 not works

### ISSUE THREAD

**Issue by diuming** [contiv/vpp#1338]
I installed contiv-vpp for kubernets 1.13.1 that It works very well.
I also create a nginx pod and a NodePort service.

checking nginx service
---
- curl 10.1.2.8:80 -> works very well(IP address refer to $ kubectl get pods -o wide)
- curl 192.168.1.11:30080 -> NodePort not works (IP address is worker node)

In the kubernetes side everything looks like normal.
How do I check this problem and how do I fix it.
thx

deployment  yaml
---
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```
service yams
---
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 443
      nodePort: 30043
      name: https
  selector:
    name: nginx
```
$ kubectl get services
---
| NAME | TYPE | CLUSTER-IP | EXTERNAL-IP | PORT(S) | AGE |
| --- | --- | --- | --- | --- | --- |
| kubernetes | ClusterIP | 10.96.0.1 | none     | 443/TCP | 2d23h |
| `nginx` | `NodePort` | 10.104.58.114 | none | `80:30080/TCP,443:30043/TCP` | 2d14h |

$ kubectl get nodes
---
| NAME | STATUS | ROLES | AGE | VERSION |
| --- | --- | --- | --- | --- |
| k8s-master1 | Ready | master | 2d23h | v1.13.1 |
| k8s-worker1 | Ready | <none> | 2d21h | v1.13.1 |

$ kubectl get pods -o wide
---
| NAME |  READY | STATUS | RESTARTS | AGE | IP | NODE |
| --- | --- | --- | --- | --- | --- | --- |
| nginx-deployment-7db75b8b78-vw6gx | 1/1 | Running | 3 | 2d15h | 10.1.2.8 | k8s-worker1 |

$ kubectl get pods -n kube-system -o wide
---
| NAME | READY | STATUS | RESTARTS | AGE | IP | NODE |
| --- | --- | --- | --- | --- | --- | --- |
| contiv-crd-kd7h8 | 1/1 | Running | 8 | 2d22h | 192.168.1.10 | k8s-master1 |
| contiv-etcd-0 | 1/1 | Running | 8 | 2d22h | 192.168.1.10 | k8s-master1 |
| contiv-ksr-pxrz4 | 1/1 | Running | 8 | 2d22h | 192.168.1.10 | k8s-master1 | 
| contiv-vswitch-2tqjw | 1/1 | Running | 17  | 2d21h | 192.168.1.11 | k8s-worker1 |
| contiv-vswitch-4zpdt | 1/1 | Running | 8 | 2d22h | 192.168.1.10 | k8s-master1 |
| coredns-86c58d9df4-mstgz | 1/1 | Running | 8 | 2d23h | 10.1.1.18 | k8s-master1 |
| coredns-86c58d9df4-q494r | 1/1 | Running | 8 | 2d23h | 10.1.1.19 | k8s-master1 |
| etcd-k8s-master1 | 1/1 | Running | 10 | 2d23h | 192.168.1.10 | k8s-master1 |
| kube-apiserver-k8s-master1 | 1/1 | Running | 10 | 2d23h | 192.168.1.10 | k8s-master1 |
| kube-controller-manager-k8s-master1 | 1/1 | Running | 10 | 2d23h | 192.168.1.10 | k8s-master1 |
| kube-proxy-9vpzr | 1/1 | Running | 8 | 2d21h | 192.168.1.11 | k8s-worker1 |
| kube-proxy-jm5gk | 1/1 | Running | 10 | 2d23h | 192.168.1.10 | k8s-master1|
| kube-scheduler-k8s-master1 | 1/1 | Running | 10 | 2d23h | 192.168.1.10 | k8s-master1 |

**Comment by rastislavszabo** [comment]
Could you please attach the bug report archive collected with this script: https://github.com/contiv/vpp/blob/master/scripts/contiv-vpp-bug-report.sh ?

Also:
 - from where are you running the curl? Master or worker node? POD or host?
 - is the clusterIP working?
 - is the nodeport working from the other node?

**Comment by diuming** [comment]
K8s-master1: 192.168.1.10
K8s-worker1: 192.168.1.11
other-host : 192.168.1.100

contiv-vpp-bug-report-2019-01-10-04-50.zip
---
[contiv-vpp-bug-report-2019-01-10-04-50.zip](https://github.com/contiv/vpp/files/2743669/contiv-vpp-bug-report-2019-01-10-04-50.zip)


Hosts to pod(10.1.2.9)
----------------------
[K8s-master1] curl 10.1.2.9:80 		-> working
[K8s-worker1] curl 10.1.2.9:80 		-> working
[other-host ] curl 10.1.2.9:80 		-> failed
              curl: (7) Failed to connect to 10.1.2.8 port 80: Operation timed out

Hosts to CLUSTER-IP(10.104.58.114)
----------------------------------
[K8s-master1] curl 10.104.58.114:80 	-> failed
              curl: (7) Failed to connect to 10.104.58.114 port 80: Connection refused
[K8s-worker1] curl 10.104.58.114:80 	-> failed
	      curl: (7) Failed to connect to 10.104.58.114 port 80: Connection refused
[other-host ] curl 10.104.58.114:80 	-> failed
	      curl: (7) Failed to connect to 10.1.2.8 port 80: Operation timed out
[K8s-master1] curl 10.104.58.114:30080 	-> failed
	      curl: (7) Failed to connect to 10.1.2.8 port 80: Operation timed out
[K8s-worker1] curl 10.104.58.114:30080 	-> failed
              curl: (7) Failed to connect to 10.1.2.8 port 80: Operation timed out
[other-host ] curl 10.104.58.114:30080 	-> failed
              curl: (7) Failed to connect to 10.1.2.8 port 80: Operation timed out

Hosts to NodePort(192.168.1.11)
----------------------------------
[K8s-master1] curl 192.168.1.11:30080 	-> failed
              curl: (7) Failed to connect to 192.168.1.11 port 30080: Connection timed out
[K8s-worker1] curl 192.168.1.11:30080 	-> failed
              curl: (7) Failed to connect to 192.168.1.11 port 30080: Connection refused
[other-host ] curl 192.168.1.11:30080 	-> failed
	      curl: (7) Failed to connect to 192.168.1.11 port 30080: Operation timed out

**Comment by rastislavszabo** [comment]
Hi,
I haven't found anything suspicious in your logs, apart from several restarts of the vswitch PODs.
Could you please try 2 more things?
- try with the latest images, we have just merged huge improvements of handling all restart scenarios,
- please try before rebooting the nodes, right after deployment

**Comment by diuming** [comment]
@rastislavszabo 
Thanks for replying!

How do I upgrade and use the latest images on kubernetes?
Sorry! I don't have any experience for that.

**Comment by rastislavszabo** [comment]
You can use this script to pull latest images (on each node):
https://github.com/contiv/vpp/blob/master/k8s/pull-images.sh

Don't forget to use the latest deployment yaml / helm chart, either git pull. If you just `kubect apply -f https://raw.githubusercontent.com/contiv/vpp/master/k8s/contiv-vpp.yaml`, you should be fine

**Comment by diuming** [comment]
@rastislavszabo thx.

I already update to latest on each node, But occur the same problem.
following are my configs, take a look, please

Q)Do I need to modify my `contiv-vpp.yaml` in segment `IPAMConfig`?
Q)Is it correct the 30080 port on tcp6? (take a look `netstat` information on k8s-worker1)
Q)Does the contiv-vpp can act as kubernetes's load balancer?
thanks for helping me!

kubeadmin init command
---
kubeadm init --token-ttl 0 --pod-network-cidr=10.1.0.0/16 --apiserver-advertise-address=192.168.1.10

My contiv-vpp.yaml
---
    IPAMConfig:
      NodeInterconnectDHCP: false
      NodeInterconnectCIDR: 192.168.16.0/24
      PodSubnetCIDR: 10.1.0.0/16
      PodNetworkPrefixLen: 24
      PodIfIPCIDR: 10.2.1.0/24
      VPPHostSubnetCIDR: 172.30.0.0/16
      VPPHostNetworkPrefixLen: 24
      VxlanCIDR: 192.168.30.0/24
    NodeConfig:
    - NodeName: "k8s-master1"
      StealInterface: "enp0s3"
    - NodeName: "k8s-worker1"
      StealInterface: "enp0s3"

[k8s-worker1] netstat -l
---
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost.localdo:33841 0.0.0.0:*               LISTEN     
tcp        0      0 localhost:domain        0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN     
tcp        0      0 localhost.localdom:9111 0.0.0.0:*               LISTEN     
tcp        0      0 localhost.localdo:10248 0.0.0.0:*               LISTEN     
tcp        0      0 localhost.localdo:10249 0.0.0.0:*               LISTEN     
tcp6       0      0 [::]:9999               [::]:*                  LISTEN     
tcp6       0      0 [::]:10256              [::]:*                  LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
tcp6       0      0 [::]:32379              [::]:*                  LISTEN     
tcp6       0      0 [::]:30080              [::]:*                  LISTEN     
tcp6       0      0 [::]:10250              [::]:*                  LISTEN     
udp        0      0 localhost:domain        0.0.0.0:*       
```

**Comment by lukasmacko** [comment]
Hi,
I think there is a typo in your service definition selector should be **app:nginx**
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 443
      nodePort: 30043
      name: https
  selector:
    app: nginx
```
with this modification it worked for me without any issues tested on contiv vagrant setup

**Comment by diuming** [comment]
@lukasmacko 
thanks you so much! It works.
Q1)can I expose it to the same as k8s-master subnet?
    ex: k8s-master: 192.168.1.10/24 nginx: 192.168.1.40:80/24
Q2)does contiv-vpp can act as `load balancer` for Kubernetes and how?

thank you!

**Comment by lukasmacko** [comment]
1, node port service can be access via vpp IP as well. You might need to add a route to access the address on vpp
```
vagrant@k8s-master:~$ sudo ip route add 192.168.16.0/24 via 172.30.1.1
vagrant@k8s-master:~$ curl 192.168.16.1:30080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
2, contiv load balances requests to service IP among its configured backends. However, it doesn't replaces external load balancer such as [metal lb](https://metallb.universe.tf/), or other cloud provider's ones

**Comment by diuming** [comment]
@lukasmacko 
Thank you for replying.

I just want to create a `private could` for internal only.
because I'm not familiar with `load balancer` and `kubernetes network`. 
So, first step I practice with NodePort service, in the future I want to get rid of NodePort than using load balancer instead.

Are these possible?
1)expose nginx to k8s-master1 subnet and using static ip address (192.168.1.400
2)Is it possible using contiv-app as `load balancer`?
thanks

**Comment by diuming** [comment]
@lukasmacko thanks for help
It works.
