### ISSUE TITLE
Vagrant Install fails

### ISSUE THREAD

**Issue by chrismetz09** [contiv/vpp#1403]
cloned, cd vpp/vagrant, ./vagrant-start then received this:

k8s-worker1: Adding Kubernetes repo...
    k8s-worker1: ++ echo 'Adding Kubernetes repo...'
    k8s-worker1: ++ curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg
    k8s-worker1: ++ sudo -E apt-key add -
    k8s-worker1: OK
    k8s-worker1: ++ sudo -E add-apt-repository 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    k8s-worker1: Adding Docker repo...
    k8s-worker1: ++ '[' 16.04 == 16.04 ']'
    k8s-worker1: ++ echo 'Adding Docker repo...'
    k8s-worker1: ++ curl -fsSL https://download.docker.com/linux/ubuntu/gpg
    k8s-worker1: ++ sudo -E apt-key add -

...

  k8s-worker1: gpg: no valid OpenPGP data found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by rastislavszabo** [comment]
Works for me. Are you still seeing this issue? Are you running this behind a proxy?

**Comment by chrismetz09** [comment]
same error. see below. Accessing via VPN from hotel room. My procedures were:
1. cloned repo
2. cd vpp/vagrant
3. ./vagrant-start
4. 2 x workers, no STN

Please advise if procedures correct.

I'll run a couple of more times after ./vagrant-cleanup to repeat error and report back.

k8s-worker1: Processing triggers for dbus (1.10.6-1ubuntu3) ...
    k8s-worker1: Processing triggers for systemd (229-4ubuntu6) ...
    k8s-worker1: Processing triggers for ureadahead (0.100.0-19) ...
    k8s-worker1: Adding Kubernetes repo...
    k8s-worker1: ++ echo 'Adding Kubernetes repo...'
    k8s-worker1: ++ curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg
    k8s-worker1: ++ sudo -E apt-key add -
    k8s-worker1: OK
    k8s-worker1: ++ sudo -E add-apt-repository 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    k8s-worker1: Adding Docker repo...
    k8s-worker1: ++ '[' 16.04 == 16.04 ']'
    k8s-worker1: ++ echo 'Adding Docker repo...'
    k8s-worker1: ++ curl -fsSL https://download.docker.com/linux/ubuntu/gpg
    k8s-worker1: ++ sudo -E apt-key add -
    k8s-worker1: curl: (6) Could not resolve host: download.docker.com
    k8s-worker1: gpg: no valid OpenPGP data found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by rastislavszabo** [comment]
The procedure is correct, the same works for me..

`Could not resolve host: download.docker.com` does not look well at all.

Could you try without VPN?

**Comment by chrismetz09** [comment]
worked san VPN! UI not working. Want to repeat a couple of times later today and will let you know results.

**Comment by lukasmacko** [comment]
What do you mean by UI not working? No response? Content missing? Inccorect data shown?
Have you setup port forwarding from vagrant machine?https://github.com/contiv/vpp/tree/master/ui#quickstart

**Comment by rastislavszabo** [comment]
not an issue anymore, vagrant works well in CI/CD pipeline
