### ISSUE TITLE
How to implement "Contiv VPP UI"?

### ISSUE THREAD

**Issue by diuming** [contiv/vpp#1412]
Hi,
I'm not familiar with `Angular CLI` and I don't have any ideas to implement `Contiv VPP UI` , so I have some questions about `Contiv VPP UI`.

q1)Do I need to install `Angular CLI`?
q2)which node is good for installation "Angular CLI"? master node or worker node.
q3)what does mean? you mentioned `ssh -F vagrant.conf -L 32500:127.0.0.1:32500 k8s-master`
thanks for helping me.

Kubernetes
---
master and worker OS: ubuntu 18.04
kubernetes environment is implemented by kubeadm.

I deployed the "contiv-vpp-ui.yaml"
---
| NAME | READY | STATUS | RESTARTS | AGE | IP | NODE |
| --- | --- | --- | --- | --- | --- | --- |
| contiv-ui-7c79455d98-mtkl6 | 0/1 | Pending |  0 | 12m | none | none |

 kubectl describe pods contiv-ui-7c79455d98-mtkl6 -n kube-system
---
```
Name:               contiv-ui-7c79455d98-mtkl6
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             pod-template-hash=7c79455d98
                    run=contiv-ui
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/contiv-ui-7c79455d98
Containers:
  ui:
    Image:      contivvpp/ui:latest
    Port:       9500/TCP
    Host Port:  0/TCP
    Environment:
      CONTIV_UI_CONF:  /etc/contiv-ui/contiv-ui.conf
    Mounts:
      /etc/contiv-ui/ from ui-cfg (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from contiv-ui-token-k2x2p (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  ui-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      contiv-ui-cfg
    Optional:  false
  contiv-ui-token-k2x2p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  contiv-ui-token-k2x2p
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  node-role.kubernetes.io/master=
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  23s (x72 over 40m)  default-scheduler  0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taints that the pod didn't tolerate.
```

**Comment by lukasmacko** [comment]
Hi,

1, no, everything required is included in contivpp/ui image
2, master ...there was an issue that master node had to be untained in order to schedule contiv-ui this should be fixed #1413 please verify once it's merged
3, the aim of the command is to forward the port (where UI is accessible) from VM to your host in order to access the UI on your localhost

thanks for reporting the issue & regards,
Lukas

**Comment by diuming** [comment]
@lukasmacko thanks for replying
everything is working except `Netctl`.
I don't use `Vagrant` to implement k8s (I use kubeadm).
Q1)Do I need to perform `ssh -F vagrant.conf -L 32500:127.0.0.1:32500 k8s-master`?
Q2)if yes. which place I need to perform it? master or my pc(browser side)?
Q3)Where I can get  vagrant.conf file?
Thanks

**Comment by lukasmacko** [comment]
okey, that's expected - netctl is kind of experimental not working currently (it will be probably removed from UI)

Since you are not using vagrant setup port forwarding command doesn't apply to your deployment.

**Comment by diuming** [comment]
@lukasmacko thanks
I got it.
