### ISSUE TITLE
[Question]Does the contiv-vpp can act as load balancer for k8s?

### ISSUE THREAD

**Issue by diuming** [contiv/vpp#1416]
does the contiv-vpp can act as load balancer for k8s? 
or do you have any plan for that in the future?
thanks.

**Comment by rastislavszabo** [comment]
Yes it does. It supports `ClusterIP` and `NodePort` [k8s services](https://kubernetes.io/docs/concepts/services-networking/service/) out of the box. `LoadBalancer` services are supported using [MetalLB](https://metallb.universe.tf/) in L2 mode, but a special build of MetalLB must be used.

**Comment by diuming** [comment]
@rastislavszabo thanks for replying
I still confuse about `MetalLB` vs `a special build of MetalLB`.
If I direct implement `MetalLB` for k8s. does it meet the `a special build of MetalLB` requirements?
or, Could you provide the manual for `a special build of MetalLB`.
thanks

**Comment by rastislavszabo** [comment]
Hi,
please see https://github.com/contiv/vpp/tree/master/k8s/metallb

**Comment by LipingMao** [comment]
@rastislavszabo : 
Looks cool, I can see the contivvpp/metallb-speaker in docker hub, any repo/dockerfile show what changed in support vpp compare with native metallb?

**Comment by rastislavszabo** [comment]
Hi, the repo is referenced from the README. 
Repo: https://github.com/google/metallb/
Diff: https://github.com/google/metallb/compare/master...ccnf:master

**Comment by diuming** [comment]
@rastislavszabo thank you for helping
I got it.
