### ISSUE TITLE
contiv-vpp pod-to-pod low performance

### ISSUE THREAD

**Issue by itaimlx** [contiv/vpp#1437]
Following the discussion in #944 and as described in https://github.com/contiv/vpp/issues/944#issuecomment-467016305
Pod-to-Pod iperf3 test result is ~2Gbits/sec over 100GB Mellanox NIC.
Opening this item to document the low performance and consult regarding the following:
- Anyone did this test on 25GB+ NIC?
- Anyone has some expected performance results for this kind of test?
- Anyone has an idea how to overcome the VPP tap bottleneck? maybe some traffic gen test container connected to the vpp vswitch over dpdk-based interface (MemIF?) ?

**Comment by rastislavszabo** [comment]
As mentioned in #944, VPP 18.04 will contain the [GSO](https://gerrit.fd.io/r/#/c/15052/) (Generic Segmentation Offload) support. That should boost the tap interface performance.

By then, you may try tweaking the iperf3 test:
- enlarge window size (e.g. `-w 1M`)
- more parallel streams (e.g. `-P 8`)
- UDP traffic (`-u`)

and as I said, running multiple parallel connections between the nodes (multiple client & server PODs).

**Comment by itaimlx** [comment]
thanks @rastislavszabo - I will try those.
Do you know of a test container utilizing high performance interface to the VPP?

**Comment by rastislavszabo** [comment]
There is a [Go libmemif implementation](https://github.com/FDio/govpp/tree/master/extras/libmemif) that could be used for writing an app that would connect to VPP via memif, and could send large amount of data to VPP via it. That could be packaged into a container and deployed as a POD - but VPP side of the memif would need to be configured somehow - e.g. via writing its config to contiv ETCD. I'm not aware of any existing container.

**Comment by itaimlx** [comment]
@rastislavszabo - just to record it:
none of the suggestions above changed, however after increasing the tap mtu by setting the mtuSize in the contiv-vpp.yaml to 9000 and playing with iperf params I was able to get:
UDP ~15 Gbits/sec using ```iperf3 -c <server> -u -b 0```
TCP ~10 Gbits/sec using ```iperf3 -c <server> -M 8900```

* parallel streams are not improving the results

**Comment by rastislavszabo** [comment]
As of the release 3.2.0, the GSO feature on VPP is enabled, which should increase pod-to-pod performance within the same node about 3x. For better DPDK performance (inter-node), multple worker threads should be used for VPP, which is tracked in https://github.com/contiv/vpp/issues/1432 and should be resolved in the next release.
