### ISSUE TITLE
Graceful shutdown of vswitch

### ISSUE THREAD

**Issue by vzelcamo** [contiv/vpp#145]

**Comment by fgschwan** [comment]
Fixed shutdown of vswitch pod. Now it removes vpp1,vpp2 interfaces in host OS and also routes connected with these interfaces.
Tested and working with manually deleting vswitch pod or deleting resources from yaml file (the one in k8s that setups networking with vswitch and vpp). Interfaces won't get removed if using only kubectl reset or node delete or node drain, so you must remove resources properly.
