### ISSUE TITLE
recovery from lost contiv-etcd

### ISSUE THREAD

**Issue by LipingMao** [contiv/vpp#1491]
Hi Team,

When I do DR test for contiv-vpp etcd, I find if I delete contiv-etcd-0 pod, the data can be regenerated, but the POD-CIDR maybe mis-match with existed POD-CIDR.  In this case, I can recovery the pods network by delete them.

Is it possible for VPP to recovery with the original POD-CIDR?

**Comment by rastislavszabo** [comment]
Duplicate of https://github.com/contiv/vpp/issues/1492
