### ISSUE TITLE
test: create multi node test on nw plugin with istio/envoy

### ISSUE THREAD

**Issue by amarcine** [contiv/vpp#153]
use nginx + curl/wget

**Comment by pgubka** [comment]
Use existing suite and modify 2 things.
- Suite setup/teardown needs to be updated with istio deployment/removal
- Replace yaml files with new ones

For istio deployment you may use:
./tests/robot/resources/istio029.yaml
Current deployment of istio is in KubernetesEnv.robot.

Existing, but not used robot suite is:
./tests/robot/suites/two_node_nginx_istio.robot
./tests/robot/suites/one_node_two_pods_with_nginx_istio.robot

For creation pods with istio you need to do e.g.
../<istio-dir>/bin/istioctl kube-inject -f nginx.yaml > nginx-injected.yaml

At the moment all is hard coded with version 0.2.9
