### ISSUE TITLE
VNF pods CrashLoopBackOff

### ISSUE THREAD

**Issue by AdelBouridah** [contiv/vpp#1554]
Hello,
After deploying contiv vpp with vagrant an deploying the SFC controller following the demo example. The deployed VNFs (1 to 4) from the example always result in a CrashLoopBackOff. 
Is this related to the VNFs YAML files or what please?

**Comment by rastislavszabo** [comment]
SFC controller demo is now superseded by SFC functionality built into Contiv-VPP CNI itself. Still work in progress, but already does something. Take a look at https://github.com/contiv/vpp/tree/master/k8s/examples/sfc
