### ISSUE TITLE
Unable to start contiv-vpp due to SINGLE NIC & vmxnet3

### ISSUE THREAD

**Issue by springwindyike** [contiv/vpp#1590]
the STN daemon is started
OS：centos7，kernel：4.18
K8s：1.11.6
-----

**configuration:**

contiv-vswitch.conf
----
unix {
   nodaemon
   cli-listen /run/vpp/cli.sock
   cli-no-pager
   poll-sleep-usec 100
}
nat {
   endpoint-dependent
   translation hash buckets 1048576
   translation hash memory 268435456
   user hash buckets 1024
   max translations per user 10000
}
acl-plugin {
   use tuple merge 0
}
api-trace {
    on
    nitems 5000
}
**dpdk {
    no-pci
}**
socksvr {
   default
}
statseg {
   default
}

contiv-vpp.yaml：
----------

data:
  contiv.conf: |-
    interfaceRxMode: "adaptive"
    stealFirstNIC: True
xxxxx
    nodeConfig:
    - nodeName: X.X.X.X
      mainVppInterface:
        interfaceName: vmxnet3-0/3/0/0
      stealInterface: enp0s8

---------
error log:
---------
  pod log:
---

time="2019-07-04 06:55:37.83475" level=debug msg="Stealing the NIC: enp0s8" loc="contiv-init/main.go(85)" logger=contiv-init
time="2019-07-04 06:55:37.83674" level=error msg="Error by executing STN GRPC: rpc error: code = Unknown desc = interface enp0s8 not found" loc="contiv-init/main.go(101)" logger=contiv-init
time="2019-07-04 06:55:37.83684" level=warning msg="Error by stealing the NIC enp0s8: rpc error: code = Unknown desc = interface enp0s8 not found" loc="contiv-init/main.go(359)" logger=contiv-init
time="2019-07-04 06:55:37.83690" level=error msg="STN configured in vswitch, but STN Daemon not initialized" loc="contiv-init/main.go(365)" logger=contiv-init

================================================================

docker logs contiv-stn:
-----
2019/07/04 06:49:19 Contiv-STN daemon, version v3.2.0, build date 2019-07-02T11:47
2019/07/04 06:49:19 Starting the STN GRPC server at socket /var/run/contiv/stn.sock
2019/07/04 06:49:57 GRPC StealInterface request: interface_name:"enp0s8"
2019/07/04 06:49:57 interface enp0s8 not found
2019/07/04 06:49:58 GRPC StealInterface request: interface_name:"enp0s8"
2019/07/04 06:49:58 interface enp0s8 not found
2019/07/04 06:50:14 GRPC StealInterface request: interface_name:"enp0s8"
2019/07/04 06:50:14 interface enp0s8 not found
2019/07/04 06:50:40 GRPC StealInterface request: interface_name:"enp0s8"
2019/07/04 06:50:40 interface enp0s8 not found
2019/07/04 06:51:23 GRPC StealInterface request: interface_name:"enp0s8"
2019/07/04 06:51:23 interface enp0s8 not found
2019/07/04 06:52:46 GRPC StealInterface request: interface_name:"enp0s8"
2019/07/04 06:52:46 interface enp0s8 not found
2019/07/04 06:55:37 GRPC StealInterface request: interface_name:"enp0s8"
2019/07/04 06:55:37 interface enp0s8 not found

sudo lshw -class network -businfo
----------
[root@node64 ~]# sudo lshw -class network -businfo
            Bus info          Device      Class      Description
pci@0000:03:00.0  ens160      network    VMXNET3 Ethernet Controller
                  virbr0      network    Ethernet interface
                  docker0     network    Ethernet interface
                  dummy0      network    Ethernet interface
                  virbr0-nic  network    Ethernet interface
                  kube-ipvs0  network    Ethernet interface

**Comment by rastislavszabo** [comment]
`stealInterface: enp0s8` is invalid. You do not have any interface with that name according to  the provided `lshw` output. Did you mean `ens160 ` ?

**Comment by springwindyike** [comment]
> `stealInterface: enp0s8` is invalid. You do not have any interface with that name according to the provided `lshw` output. Did you mean `ens160 ` ?
----------
contiv-vswitch.conf
---
 unix {
   nodaemon
   cli-listen /run/vpp/cli.sock
   cli-no-pager
   poll-sleep-usec 100
}
nat {
   endpoint-dependent
   translation hash buckets 1048576
   translation hash memory 268435456
   user hash buckets 1024
   max translations per user 10000
}
acl-plugin {
   use tuple merge 0
}
api-trace {
    on
    nitems 5000
}
dpdk {
   dev 0000:03:00.0
}
socksvr {
   default
}
statseg {
   default
}

contiv-vpp:
---
    interfaceRxMode: "adaptive"
    tcpChecksumOffloadDisabled: true
    STNVersion: 2
    natExternalTraffic: true
    mtuSize: 1450
    scanIPNeighbors: true
    ipNeighborScanInterval: 1
    ipNeighborStaleThreshold: 4
    enablePacketTrace: false
    routeServiceCIDRToVPP: false
    crdNodeConfigurationDisabled: true
    ipamConfig:
      nodeInterconnectDHCP: false
      nodeInterconnectCIDR: 192.168.16.0/24
      podSubnetCIDR: 10.254.0.0/16
      podSubnetOneNodePrefixLen: 24
      vppHostSubnetCIDR: 172.30.0.0/16
      vppHostSubnetOneNodePrefixLen: 24
      vxlanCIDR: 192.168.30.0/24
      srv6:
        servicePolicyBSIDSubnetCIDR: 5555::/16
        servicePodLocalSIDSubnetCIDR: 6666::/16
        serviceHostLocalSIDSubnetCIDR: 6655::/16
        serviceNodeLocalSIDSubnetCIDR: 7766::/16
        nodeToNodePodLocalSIDSubnetCIDR: 7777::/16
        nodeToNodeHostLocalSIDSubnetCIDR: 7799::/16
        nodeToNodePodPolicySIDSubnetCIDR: 8888::/16
        nodeToNodeHostPolicySIDSubnetCIDR: 9999::/16
    nodeConfig:
    - nodeName: 192.168.101.64
      stealInterface: ens160
    - nodeName: 192.168.101.65
      stealInterface: ens192
    - nodeName: 192.168.101.67
      stealInterface: ens192

if use ens160
--------
error：
-------
pod error:
time="2019-07-04 13:18:48.51028" level=debug msg="/usr/bin/vpp[19377]: load_one_vat_plugin:67: Loaded plugin: stn_test_plugin.so\n" loc="contiv-init/vpplogger.go(23)" logger=vpp
time="2019-07-04 13:18:48.51038" level=debug msg="/usr/bin/vpp[19377]: load_one_vat_plugin:67: Loaded plugin: vmxnet3_test_plugin.so\n" loc="contiv-init/vpplogger.go(23)" logger=vpp
time="2019-07-04 13:18:48.57620" level=debug msg="/usr/bin/vpp[19377]: vlib_pci_bind_to_uio: Skipping PCI device 0000:03:00.0: missing kernel VFIO or UIO driver\n/usr/bin/vpp[19377]: dpdk: EAL init args: -c 2 -n 4 --in-memory --file-prefix vpp --master-lcore 1 \n" loc="contiv-init/vpplogger.go(23)" logger=vpp
time="2019-07-04 13:18:51.31973" level=error msg="VPP terminated, stopping contiv-agent" loc="contiv-init/main.go(440)" logger=contiv-init
time="2019-07-04 13:18:51.32012" level=info msg="Signal terminated received during agent start, stopping" loc="agent/agent.go(153)" logger=agent
time="2019-07-04 13:18:51.32312" level=debug msg=exiting loc="contiv-init/main.go(453)" logger=contiv-init
time="2019-07-04 13:18:51.32323" level=debug msg="Releasing the NIC: ens160" loc="contiv-init/main.go(111)" logger=contiv-init
time="2019-07-04 13:18:51.53093" level=debug loc="contiv-init/main.go(131)" logger=contiv-init


docker logs contiv-stn
-------
error:
---------
2019/07/04 13:23:10 (non-fatal) error by deleting interface ens160 route to fe80::/64: no such process
2019/07/04 13:23:10 (non-fatal) error by deleting interface ens160 IP fe80::ef21:dad2:c690:61e9/64: cannot assign requested address
2019/07/04 13:23:10 Unbinding 0000:03:00.0 from its current driver
2019/07/04 13:23:10 Writing '0000:03:00.0' into file /sys/bus/pci/devices/0000:03:00.0/driver/unbind
2019/07/04 13:23:10 Binding 0000:03:00.0 to driver vfio-pci
2019/07/04 13:23:10 Writing '15ad  7b0' into file /sys/bus/pci/drivers/vfio-pci/new_id
2019/07/04 13:23:10 Writing '0000:03:00.0' into file /sys/bus/pci/drivers/vfio-pci/bind
2019/07/04 13:23:10 (non-fatal) error by writing to /sys/bus/pci/drivers/vfio-pci/bind: write /sys/bus/pci/drivers/vfio-pci/bind: no such device
2019/07/04 13:23:10 Returning GRPC data: pci_address:"0000:03:00.0" ip_addresses:"192.168.101.64/21" ip_addresses:"fe80::ef21:dad2:c690:61e9/64" routes:<next_hop_ip:"192.168.100.1" > routes:<destination_subnet:"192.168.96.0/21" > routes:<destination_subnet:"fe80::/64" > kernel_driver:"vmxnet3"
2019/07/04 13:23:12 GRPC ReleaseInterface request: interface_name:"ens160"
2019/07/04 13:23:12 Reverting interface ens160
2019/07/04 13:23:12 Unbinding 0000:03:00.0 from its current driver
2019/07/04 13:23:12 Writing '0000:03:00.0' into file /sys/bus/pci/devices/0000:03:00.0/driver/unbind
2019/07/04 13:23:12 error by opening /sys/bus/pci/devices/0000:03:00.0/driver/unbind: open /sys/bus/pci/devices/0000:03:00.0/driver/unbind: no such file or directory
2019/07/04 13:23:12 Binding 0000:03:00.0 to driver vmxnet3
2019/07/04 13:23:12 Writing '15ad  7b0' into file /sys/bus/pci/drivers/vmxnet3/new_id
2019/07/04 13:23:12 (non-fatal) error by writing to /sys/bus/pci/drivers/vmxnet3/new_id: write /sys/bus/pci/drivers/vmxnet3/new_id: file exists
2019/07/04 13:23:12 Writing '0000:03:00.0' into file /sys/bus/pci/drivers/vmxnet3/bind
2019/07/04 13:23:12 IP link lookup attempt 1 failed, retry
2019/07/04 13:23:12 Setting interface ens160 (idx 14) to UP state
2019/07/04 13:23:12 Adding IP address 192.168.101.64/21 ens160 to interface ens160 (idx 14)
2019/07/04 13:23:12 ens160: IP 192.168.101.64 already exists, skipping
2019/07/04 13:23:12 Adding IP address fe80::ef21:dad2:c690:61e9/64 to interface ens160 (idx 14)
2019/07/04 13:23:12 ens160: IP fe80::ef21:dad2:c690:61e9 already exists, skipping
2019/07/04 13:23:12 Adding route via interface ens160: {Ifindex: 14 Dst: <nil> Src: <nil> Gw: 192.168.100.1 Flags: [] Table: 254}
2019/07/04 13:23:12 ens160: route already exists, skipping ({Ifindex: 14 Dst: <nil> Src: <nil> Gw: 192.168.100.1 Flags: [] Table: 254})
2019/07/04 13:23:12 Adding route via interface ens160: {Ifindex: 14 Dst: 192.168.96.0/21 Src: 192.168.101.64 Gw: <nil> Flags: [] Table: 254}
2019/07/04 13:23:12 ens160: route already exists, skipping ({Ifindex: 14 Dst: 192.168.96.0/21 Src: 192.168.101.64 Gw: <nil> Flags: [] Table: 254})
2019/07/04 13:23:12 Adding route via interface ens160: {Ifindex: 14 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}
2019/07/04 13:23:12 ens160: route already exists, skipping ({Ifindex: 14 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254})
2019/07/04 13:23:15 Checking state of the interface ens160
2019/07/04 13:23:15 Interface ens160 is in desired state.
2019/07/04 13:23:40 IP link lookup attempt 1 failed, retry
2019/07/04 13:23:40 IP link lookup attempt 2 failed, retry
2019/07/04 13:23:40 IP link lookup attempt 3 failed, retry
2019/07/04 13:23:40 IP link lookup attempt 4 failed, retry
2019/07/04 13:23:41 IP link lookup attempt 5 failed, retry
2019/07/04 13:23:41 IP link lookup attempt 6 failed, retry
2019/07/04 13:23:41 IP link lookup attempt 7 failed, retry
2019/07/04 13:23:41 IP link lookup attempt 8 failed, retry
2019/07/04 13:23:41 IP link lookup attempt 9 failed, retry
2019/07/04 13:23:42 IP link lookup attempt 10 failed, retry
2019/07/04 13:23:42 IP link lookup attempt 11 failed, retry
2019/07/04 13:23:42 IP link lookup attempt 12 failed, retry
2019/07/04 13:23:42 IP link lookup attempt 13 failed, retry
2019/07/04 13:23:42 IP link lookup attempt 14 failed, retry
2019/07/04 13:23:43 IP link lookup attempt 15 failed, retry
2019/07/04 13:23:43 IP link lookup attempt 16 failed, retry
2019/07/04 13:23:43 IP link lookup attempt 17 failed, retry
2019/07/04 13:23:43 IP link lookup attempt 18 failed, retry
2019/07/04 13:23:43 IP link lookup attempt 19 failed, retry
2019/07/04 13:23:44 Error by looking up for interface vpp1: Link not found
2019/07/04 13:23:44 Error by looking up for interface vpp1: Link not found

**Comment by rastislavszabo** [comment]
`/usr/bin/vpp[19377]: vlib_pci_bind_to_uio: Skipping PCI device 0000:03:00.0: missing kernel VFIO or UIO driver`
Please make sure you have the vfio driver loaded.

**Comment by springwindyike** [comment]
> `/usr/bin/vpp[19377]: vlib_pci_bind_to_uio: Skipping PCI device 0000:03:00.0: missing kernel VFIO or UIO driver`
> Please make sure you have the vfio driver loaded.

------

thinks，The problem is solved。
