### ISSUE TITLE
Multus compatibility

### ISSUE THREAD

**Issue by Gylleus** [contiv/vpp#1670]
Are there any plans to be compatible with running together with other CNI plugins in Kubernetes through Multus for example? Currently Contiv VPP removes all other CNI configuration files when deployed though the `install.sh` script in `vpp-cni`:

```bash
# Erase all existing CNI config files.
echo "Erasing old CNI config in ${HOST_CNI_NET_DIR}"
rm -rf ${HOST_CNI_NET_DIR}/*
```

Our current use case is to use Multus for network separation, having one conventional CNI for slow path and Contiv for fast path which as of now seems to require some workarounds.

Sorry if this question has been asked before but I could not find any answers when searching.

**Comment by Gylleus** [comment]
Any thoughts on this @rastislavszabo ?

I could make some simple pull request to toggle the clean-up of CNI configuration if there is any interest.

**Comment by rastislavszabo** [comment]
Hi @Gylleus , sure, feel free to open a PR.
I guess we should be good enough with removing the contiv-vpp conf file.
