### ISSUE TITLE
Support for tenants

### ISSUE THREAD

**Issue by holoGDM** [contiv/vpp#1753]
Do ContiVpp have support for [tenants](https://contiv.io/documents/admin/createTenant.html) like contiv for separating networks/users?

I found such [PR]( https://github.com/contiv/vpp/pull/945) are VRFs same thing what tenants are for contiv if yes where can i find how to use it or when it will be officially supported?

/question

**Comment by gilesheron** [comment]
I don't believe so.   Technically it'd be relatively straightfoward as the client overlay and the transport underlay are in different VRFs so it'd be a case of spinning up one VRF per tenant.

Contiv-VPP is no longer being actively developed.  Equally if you'd like to contribute code that's ok :)

**Comment by holoGDM** [comment]
Thanks for reply. I think i found solution which will suits my requirements [kube-ovn](https://github.com/alauda/kube-ovn) instead
