### ISSUE TITLE
test: kube cluster cleanup & pull images

### ISSUE THREAD

**Issue by amarcine** [contiv/vpp#194]
kubeadm reset + docker clean (images +containers) move to setup teardown lib

image names should be in variables.robot, instead of running pull script, run separated pull commands for each image

yaml resource files should have variables as image name

reset, clean and pull ust work in multinode cluster

**Comment by vrpolakatcisco** [comment]
When trying to implement reset suites, I was testing https://github.com/vrpolakatcisco/vpp/tree/contiv194_201/tests/robot/suites
suites 00_kubeadm_reset.robot and zz_docker_purge.robot

**Comment by amarcine** [comment]
todo:
add to cleanup
docker images | fgrep contiv | fgrep days | fgrep -v proxy | awk '{print $3}' | sort -u | xargs docker rmi -f
