### ISSUE TITLE
LD preload ngnix 

### ISSUE THREAD

**Issue by vzelcamo** [contiv/vpp#284]

**Comment by pgubka** [comment]
new job is needed to run this or add a suite robot file into existing job (append suite for pybot command)

the suite is in: tests/robot/suites/two_node_nginx_ldpreload.robot
config yaml files are:
tests/robot/resources/ubuntu-client-ldpreload-node1.yaml
tests/robot/resources/nginx-ldpreload-node2.yaml

One thing that is should/might be changed is a part of yam file:
        env:
          # ldpreload-related env vars
          - name: VCL_APP_SCOPE_GLOBAL
            value: ""
For proper setup check with k8s/examples/ldpreload/nginx/* , as it is still under development

**Comment by vrpolakatcisco** [comment]
The suite should now be running due to https://github.com/contiv/vpp/issues/318
Will update the yaml files soon.

**Comment by vrpolakatcisco** [comment]
Yamls updated, closing.
