### ISSUE TITLE
test: Use docker exec instead of kubectl exec in tests

### ISSUE THREAD

**Issue by vzelcamo** [contiv/vpp#317]

**Comment by vrpolakatcisco** [comment]
Pull request created: https://github.com/contiv/vpp/pull/319
Jenkins jobs still need to get reconfigured.

**Comment by vrpolakatcisco** [comment]
The above comment was intended for https://github.com/contiv/vpp/issues/318

**Comment by vrpolakatcisco** [comment]
Done.

**Comment by vrpolakatcisco** [comment]
Done
