### ISSUE TITLE
test: Run all tests in single jenkins

### ISSUE THREAD

**Issue by vzelcamo** [contiv/vpp#318]
v jenkinse momentalne potrebujeme pomenit imidze na vmkach za tie kde je fixnute dns, niektore uz su ale nie vsetky, tak to nevieme cele otestit

+ peto ma aj zakomentovane niektore dns testy koli tomu ze blblo to dns na tych nasich imidzoch, to tiez treba odkomentit

**Comment by vrpolakatcisco** [comment]
https://github.com/contiv/vpp/pull/319 merged, jenkins job created: http://10.52.232.163:8080/job/test_all_robot_suites/2/console

Old jobs are left there till history is relevant.
