### ISSUE TITLE
agent crash/restart scenario support

### ISSUE THREAD

**Issue by rastislavszabo** [contiv/vpp#434]

**Comment by lukasmacko** [comment]
The following issues has to be addressed in order to support agent restart:
- config of host end of TAP is not persisted
- the order routes in pod (link scope route has to be configured before default route)
- persist IPAM state

**Comment by rastislavszabo** [comment]
another potential issue:
 - resync implementation in linuxplugin

**Comment by rastislavszabo** [comment]
already implemented
