### ISSUE TITLE
Vagrantfile is not working

### ISSUE THREAD

**Issue by kahou82** [contiv/vpp#469]
I ran the vagrant file and it only generate k8s-master. The following is the last couple message from Vagrant output

`==> k8s-master: clusterrole "contiv-ksr" created
==> k8s-master: serviceaccount "contiv-ksr" created
==> k8s-master: clusterrolebinding "contiv-ksr" created
==> k8s-master: Schedule Pods on master
==> k8s-master: node "k8s-master" untainted`

Also, when I run kubectl command it will return the following:

`vagrant@k8s-master:~$ kubectl get pods
Unable to connect to the server: dial tcp 192.169.1.10:6443: i/o timeout`

**Comment by jmedved** [comment]
+ Nikos

**Comment by brecode** [comment]
@kahou82 

Do you run it using the vagrant-up.sh script? Is this for a single or 2-node setup?

**Comment by jmedved** [comment]
I was able to bring it up on my Mac, it worked out of the box. 

We had one issue - after ungraceful shutdown of the machine, networking between hosts got borked because Linux started taking ownership of VPP's interface. Nikos is working on a fix.

**Comment by jmedved** [comment]
@kahou82, @brecode

I was able to bring it up on my Mac, it worked out of the box.

We had one issue - after ungraceful shutdown of the machine, networking between hosts got borked because Linux started taking ownership of VPP's interface. Nikos is working on a fix.

**Comment by brecode** [comment]
@kahou82 @jmedved 

The fix for shutdown/restarts has been merged. Also added a README file with instructions and two more scripts for shutdown and restart of the k8s cluster.

**Comment by kahou82** [comment]
Thanks, looks like I was using vagrant up only and that causes trouble. I am able to stand up a 2 nodes cluster now.
