### ISSUE TITLE
contiv-init keeps seg faulting 

### ISSUE THREAD

**Issue by mercion** [contiv/vpp#814]
contiv-init keeps crashing on me with the following error ...

```
2018-05-28 14:14:12,452 DEBG 'contiv-init' stdout output:
time="2018-05-28T14:14:12Z" level=debug msg="API channel closed." context=2

2018-05-28 14:14:12,455 DEBG 'contiv-init' stdout output:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 
2018-05-28 14:14:12,455 DEBG 'contiv-init' stdout output:
SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10b56b6]

goroutine 1 [running]:
main.configureVpp(0xc4203e2dd0, 0xc4204f4180, 0x2300, 0x0, 0x0, 0x0)
	/root/go/src/github.com/contiv/vpp/cmd/contiv-init/vppcfg.go
2018-05-28 14:14:12,455 DEBG 'contiv-init' stdout output:
:260 +0x1806
main.main()
	/root/go/src/github.com/contiv/vpp/cmd/contiv-init/main.go:239 +0x971
```

contiv-vpp on a ubunutu vm running k8s.

**Comment by mercion** [comment]
Seems to happen if you dont have DHCP enabled (NodeInterconnectDHCP).  Might not be a bug here but it is a little confusing.

**Comment by jmedved** [comment]
Are you trying to use the single-NIC configuration or the two-NIC configuration? The crash indicates that the STN daemon is not running - but that's only required in the single-NIC configuration. 

Please give more details about your configuration (both the VPP config and the contiv-VPP config in contv-vpp.yaml) and the steps you executed when bringing up the cluster.

**Comment by rastislavszabo** [comment]
Fixed
