### ISSUE TITLE
vEth interfaces performance

### ISSUE THREAD

**Issue by edsealing** [contiv/vpp#928]
HW: VMware 6.5 VMs (vmxnet3 NICs)
OS: CentOS 17.08
Kernel: 3.10.0-693.el7.x86_64
Contiv-VPP Build: latest (as of 7/3/2018)

I've been doing some installation and performance testing on CentOS using iperf3 containers. The initial goal was to see what the performance of intra-node containers are using VPP with both TAPv2 and AF-Packet (veth) interfaces.

[contiv-vpp.yaml](https://github.com/contiv/vpp/files/2161730/contiv-vpp.txt)
[iperf-server.yaml](https://github.com/contiv/vpp/files/2161734/iperf-server.yaml.txt)
[iperf-client.yaml](https://github.com/contiv/vpp/files/2161733/iperf-client.yaml.txt)

When using TAPv2, I'm getting ~2.1 Gbps between containers on the same node.
However when using veth interfaces, I'm only seeing ~20 Mbps. These results are the same when setting `TCPstackDisabled: True` and `TCPstackDisabled: False`. I would have expected the AF_PACKET throughput to be significantly higher than TAP interfaces.

Also, I've noticed the CRI-shim has been commented out in a bunch of places in the code. A lot of the documentation still makes reference to it. Is this now deprecated? (if so, I can submit a PR to pull it out of the difference documentation areas)

Thanks.

**Comment by rastislavszabo** [comment]
Hi,
your results are actually expected, TAPv2 interfaces on VPP (virtio-based) are supposed to be much faster than AF_PACKET. Better performance was the reason for introducing them to VPP and making them default instead of veths in Contiv/VPP.

Yes, CRI shim, as well as TCP stack on VPP has been deprecated. Feel free to cleanup the doc, we would welcome your PRs.

**Comment by rastislavszabo** [comment]
Hi,
currently there is no high-speed alternative to deprecated LDPRELOAD. We are currently focusing on improving the stability of the plugin. Once that is done, we mat re-start work on high-speed alternatives.

**Comment by junxiaocne** [comment]
@rastislavszabo would you please elaborate the reasons for LDPRELOAD was deprecated? thanks!
