### ISSUE TITLE
contiv-vpp is unable to steal the NIC

### ISSUE THREAD

**Issue by acloudiator** [contiv/vpp#938]
Hi All,

I'm trying to use the contiv-vpp in my local setup. Setup and things all went well but the problem occurs when I try to ping the `pod IP` from a different node, from the same node, it's working well.

Any help would be highly appreciated. Thanks!

```
al-server-a:~$ ping 10.1.1.2 -c 2
PING 10.1.1.2 (10.1.1.2) 56(84) bytes of data.
64 bytes from 10.1.1.2: icmp_seq=1 ttl=63 time=0.405 ms
64 bytes from 10.1.1.2: icmp_seq=2 ttl=63 time=0.341 ms

--- 10.1.1.2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1028ms
rtt min/avg/max/mdev = 0.341/0.373/0.405/0.032 ms
```

```
al-server-a:~$ ping 10.1.2.6 -c 2
PING 10.1.2.6 (10.1.2.6) 56(84) bytes of data.

--- 10.1.2.6 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1031ms
```

```
$ kubectl get po --all-namespaces -o wide
NAMESPACE     NAME                                  READY     STATUS             RESTARTS   AGE       IP          NODE
default       alpine-q5vkp                          1/1       Running            0          3m        10.1.1.2    al-server-a
default       alpine-rhg9j                          1/1       Running            0          2m        10.1.2.6    al-blacknode-a
kube-system   contiv-etcd-0                         1/1       Running            0          7m        1.2.3.10    al-server-a
kube-system   contiv-ksr-7lk5p                      1/1       Running            0          7m        1.2.3.10    al-server-a
kube-system   contiv-vswitch-hmwt2                  1/1       Running            0          7m        1.2.3.100   al-blacknode-a
kube-system   contiv-vswitch-lvfwv                  1/1       Running            0          7m        1.2.3.10    al-server-a
kube-system   etcd-al-server-a                      1/1       Running            0          24m       1.2.3.10    al-server-a
kube-system   kube-apiserver-al-server-a            1/1       Running            0          24m       1.2.3.10    al-server-a
kube-system   kube-controller-manager-al-server-a   1/1       Running            0          24m       1.2.3.10    al-server-a
kube-system   kube-dns-86f4d74b45-kxt4z             3/3       Running            0          24m       1.2.3.10    al-server-a
kube-system   kube-proxy-f86hw                      1/1       Running            0          24m       1.2.3.100   al-blacknode-a
kube-system   kube-proxy-tl56k                      1/1       Running            0          25m       1.2.3.10    al-server-a
kube-system   kube-scheduler-al-server-a            1/1       Running            0          24m       1.2.3.10    al-server-a
```

**Comment by acloudiator** [comment]
Thanks @rastislavszabo for your response! I've checked logs and there isn't any error related to `0000:01:00.1` interface.

CLI with args for VPP
`/usr/bin/vpp[17562]: dpdk: EAL init args: -c 2 -n 4 --huge-dir /run/vpp/hugepages --file-prefix vpp -w 0000:01:00.1 --master-lcore 1 --socket-mem 64`

Any further hints to identify the cause? Thanks!

**Comment by acloudiator** [comment]
Hi @jmedved,

Yes, It's a bare metal and setup with kubeadm.

1. OS & Arch: `Ubuntu 16.04.4 LTS` (x86_64)
2. Kernel: `4.15.0-041500-generic`
3. kubeadm init cli: `kubeadm init --token-ttl 0 --pod-network-cidr=10.1.0.0/16 --apiserver-advertise-address=1.2.3.10`
4. kubernetes version: `v1.10.3`
5. docker version: `v18.3.1`

**Comment by jmedved** [comment]
VPP is not taking over the NIC for some reason, as Rasto pointed out. The issue can be with the NIC - can you please let us know the type (and potentially configuration) of the  NIC card (or is a GigE on the motherboard?). 

Also, can you please try to remove the 'poll-sleep-usec 100' line from the VPP config - that's there mostly for a VM deployment, we haven't tested this configuration on bare metal.

**Comment by acloudiator** [comment]
Thanks for that dpdk driver command! The link was down before deploying the contiv-vpp.

Checking with the dpdk-devbind.py, I found that the NIC is not assigned for DPDK and manually adding is failing with an error.

```
$ ./dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
<none>

Network devices using kernel driver
===================================
0000:00:1f.6 'Ethernet Connection (2) I219-V' if=enp0s31f6 drv=e1000e unused=uio_pci_generic
0000:01:00.0 'Device 158b' if=enp1s0f0 drv=i40e unused=uio_pci_generic
0000:01:00.1 'Device 158b' if=enp1s0f1 drv=i40e unused=uio_pci_generic
0000:03:00.0 'AR9287 Wireless Network Adapter (PCI-Express)' if=wlp3s0 drv=ath9k unused=uio_pci_generic

Other network devices
=====================
0000:02:00.0 'BCM4352 802.11ac Wireless Network Adapter' unused=bcma,uio_pci_generic

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>
```

```
$ sudo ./dpdk-devbind.py --bind=uio_pci_generic 01:00.1
Error: bind failed for 0000:01:00.1 - Cannot bind to driver uio_pci_generic
Error: unbind failed for 0000:01:00.1 - Cannot open /sys/bus/pci/drivers//unbind
```

**Comment by sluong99** [comment]
lsmod | grep uio_pci_generic
If it is not loaded, use modprobe to load it.

**Comment by acloudiator** [comment]
it's already loaded

```
$ sudo lsmod | grep uio_pci_generic
uio_pci_generic        16384  0
uio                    20480  1 uio_pci_generic
```

**Comment by acloudiator** [comment]
Tried vfio-pci and it throw an error

```
$ lsmod | grep -i vfio
vfio_pci               45056  0
vfio_virqfd            16384  1 vfio_pci
vfio_iommu_type1       24576  0
vfio                   28672  2 vfio_iommu_type1,vfio_pci
irqbypass              16384  2 kvm,vfio_pci
```
```
$ sudo ./dpdk-devbind.py --bind=vfio_pci 01:00.1
Error: bind failed for 0000:01:00.1 - Cannot open /sys/bus/pci/drivers/vfio_pci/bind
```
I found something on internet, that I have to set `iommu=pt` `intel_iommu=on`. I will try this and then re-bind with vfio_pci. Will update the progress shortly.

**Comment by sluong99** [comment]
sudo ./dpdk-devbind.py --bind=vfio-pci 01:00.1

Please note it is vfio-pci, not vfio_pci.

**Comment by sluong99** [comment]
Check the errors at the end of dmesg

**Comment by acloudiator** [comment]
[ 2160.844379] i40e 0000:01:00.1: i40e_ptp_stop: removed PHC on enp1s0f1

**Comment by sluong99** [comment]
It looks like you got an Intel XXV710 adapter. I've never played with this one. Try modprobe igb_uio and bind it to igb_uio.

I have an XL710 and I am able to bind it to either vfio-pci or igb_uio. Maybe yours takes only igb_uio.

**Comment by acloudiator** [comment]
Thank you @sluong99 !! igb_uio worked.

`$ sudo ./dpdk-devbind.py --bind=igb_uio 01:00.1`

```
$ ./dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0000:01:00.1 'Device 158b' drv=igb_uio unused=i40e,uio_pci_generic
```

I will now re-run the contiv-vpp setup on Kubernetes. Thank you once again !

**Comment by acloudiator** [comment]
Now the contiv-vpp setup seems to be functional, but failing for nodeport and clusterIP service.

- I would rather close this ticket and open new one for other issue.

Thanks @sluong99 and all!

**Comment by rastislavszabo** [comment]
Hi,
if you are deploying Contiv/VPP in STN (Steal the NIC) mode, there are few known issues related to nodePort and clusterIP services. They only manisfet themselves in STN mode, not in 2-NIC mode. The STN issues should be fixed after https://github.com/contiv/vpp/pull/945 is merged.

**Comment by acloudiator** [comment]
Great! I would test it after it's merged.

**Comment by rastislavszabo** [comment]
#945 merged, please give it a try.

**Comment by acloudiator** [comment]
Caught up with some other work and I should come back here again (maybe next week) to try #945
