### ISSUE TITLE
Would You Please Help Upload ContivVPP-arm64 Docker Images to Official Docker Repo

### ISSUE THREAD

**Issue by TrevorTaoARM** [contiv/vpp#994]
Hi:
Now Contiv/VPP arm64 docker images can be built by the command:
docker/build-all.sh
on arm64 platform.
And we are committing the sample deployment yaml file for arm64 as contiv-vpp-arm64.yaml:
https://github.com/contiv/vpp/pull/1002

So could you please help build and upload the corresponding contivvpp arm64 docker images, such as 
contivvpp/ksr-arm64, contivvpp/cni-arm64, contivvpp/vswitch-arm64 to facilitate its deployment on arm64 platform.
Any question or request is welcome.

**Comment by rastislavszabo** [comment]
Hi,
we cannot really help with building ARM images, wince we do not have any spare ARM server that could be used for builds. However, I we create appropriate repos on Dockerhub and give you write access to them if you want to setup build on your infra. Just let me know, e.g. via Slack (https://contivvpp.slack.com/):

https://join.slack.com/t/contivvpp/shared_invite/enQtNDE0MDk3NzAxOTc0LThmZDlmYTRlMWExZjUyNWIyMGQ3YjgxMzA1NjFhNjk1ZjIwNGRmNmE5Mzc1OWI1MTI3ZjM4NTQ3ZWI2YTQ3ODM

**Comment by TrevorTaoARM** [comment]
@rastislavszabo 
For our company's policy, I can not upload docker images directly. But we may do it via our 3rd party partners to do it.  I will contact them for this issue and respond to you after that.
Thanks a lot.

**Comment by stanislav-chlebec** [comment]
We are solving that.

**Comment by TrevorTaoARM** [comment]
Images are uploaded now.
